"""empty message

Revision ID: 158faa90811c
Revises: 
Create Date: 2017-02-28 11:58:22.318974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158faa90811c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teams')
    # ### end Alembic commands ###
