"""empty message

Revision ID: 3fc5b032f1f8
Revises: 7d8ff5a534e5
Create Date: 2017-03-03 14:44:55.913052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc5b032f1f8'
down_revision = '7d8ff5a534e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixture', sa.Column('league_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'fixture', 'league', ['league_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fixture', type_='foreignkey')
    op.drop_column('fixture', 'league_id')
    # ### end Alembic commands ###
