"""empty message

Revision ID: 5f962fc41786
Revises: 3fc5b032f1f8
Create Date: 2017-03-07 10:54:36.733687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f962fc41786'
down_revision = '3fc5b032f1f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixture', sa.Column('fulltime_result', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixture', 'fulltime_result')
    # ### end Alembic commands ###
