"""empty message

Revision ID: 61948a23ee75
Revises: 91527c7cdbe3
Create Date: 2017-03-22 12:19:21.680103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61948a23ee75'
down_revision = '91527c7cdbe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('league_name_slug_key', 'league', type_='unique')
    op.create_unique_constraint(None, 'league', ['name'])
    op.create_unique_constraint(None, 'league', ['slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league', type_='unique')
    op.drop_constraint(None, 'league', type_='unique')
    op.create_unique_constraint('league_name_slug_key', 'league', ['name', 'slug'])
    # ### end Alembic commands ###
