"""empty message

Revision ID: 825324641212
Revises: a13b8aee3f3c
Create Date: 2017-03-09 11:27:05.245763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825324641212'
down_revision = 'a13b8aee3f3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fixture_id', sa.Integer(), nullable=True),
    sa.Column('home_goals', sa.Float(), nullable=True),
    sa.Column('away_goals', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['fixture_id'], ['fixture.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    # ### end Alembic commands ###
