"""empty message

Revision ID: 8d21f56b3f0b
Revises: abbf3edb3509
Create Date: 2017-03-21 11:29:03.946270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d21f56b3f0b'
down_revision = 'abbf3edb3509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('betfair_name', sa.String(length=200), nullable=True))
    op.add_column('teams', sa.Column('betfair_name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'betfair_name')
    op.drop_column('league', 'betfair_name')
    # ### end Alembic commands ###
