"""empty message

Revision ID: 91527c7cdbe3
Revises: 9f9eee72fcd7
Create Date: 2017-03-22 12:18:04.732575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91527c7cdbe3'
down_revision = '9f9eee72fcd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('league_name_key', 'league', type_='unique')
    op.create_unique_constraint(None, 'league', ['name', 'slug'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league', type_='unique')
    op.create_unique_constraint('league_name_key', 'league', ['name'])
    # ### end Alembic commands ###
