"""empty message

Revision ID: 9f9eee72fcd7
Revises: 8d21f56b3f0b
Create Date: 2017-03-22 11:49:55.408972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f9eee72fcd7'
down_revision = '8d21f56b3f0b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'league', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'league', type_='unique')
    # ### end Alembic commands ###
