"""empty message

Revision ID: a13b8aee3f3c
Revises: 995116c4b8dd
Create Date: 2017-03-08 15:24:58.112462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a13b8aee3f3c'
down_revision = '995116c4b8dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_stats', sa.Column('away_attack_strength', sa.Float(), nullable=True))
    op.add_column('team_stats', sa.Column('away_defense_strength', sa.Float(), nullable=True))
    op.add_column('team_stats', sa.Column('home_attack_strength', sa.Float(), nullable=True))
    op.add_column('team_stats', sa.Column('home_defense_strength', sa.Float(), nullable=True))
    op.drop_column('team_stats', 'attack_strength')
    op.drop_column('team_stats', 'defense_strength')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_stats', sa.Column('defense_strength', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('team_stats', sa.Column('attack_strength', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('team_stats', 'home_defense_strength')
    op.drop_column('team_stats', 'home_attack_strength')
    op.drop_column('team_stats', 'away_defense_strength')
    op.drop_column('team_stats', 'away_attack_strength')
    # ### end Alembic commands ###
