"""empty message

Revision ID: a95795347d86
Revises: ff95ea9abd2f
Create Date: 2017-03-07 15:20:29.683692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95795347d86'
down_revision = 'ff95ea9abd2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('league', sa.Column('slug', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('league', 'slug')
    # ### end Alembic commands ###
