"""empty message

Revision ID: b2113bcd574e
Revises: e3eb8d9b0117
Create Date: 2017-03-01 14:44:02.500171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2113bcd574e'
down_revision = 'e3eb8d9b0117'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('drawn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'drawn')
    # ### end Alembic commands ###
