"""empty message

Revision ID: cf07dafc6f26
Revises: dde51f5720c0
Create Date: 2017-03-13 12:03:31.577286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf07dafc6f26'
down_revision = 'dde51f5720c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'position')
    # ### end Alembic commands ###
