"""empty message

Revision ID: dde51f5720c0
Revises: 825324641212
Create Date: 2017-03-09 15:15:53.268291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dde51f5720c0'
down_revision = '825324641212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction', sa.Column('away_goals_pmf', sa.PickleType(), nullable=True))
    op.add_column('prediction', sa.Column('away_win', sa.Float(), nullable=True))
    op.add_column('prediction', sa.Column('draw', sa.Float(), nullable=True))
    op.add_column('prediction', sa.Column('home_goals_pmf', sa.PickleType(), nullable=True))
    op.add_column('prediction', sa.Column('home_win', sa.Float(), nullable=True))
    op.add_column('prediction', sa.Column('over', sa.Float(), nullable=True))
    op.add_column('prediction', sa.Column('under', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prediction', 'under')
    op.drop_column('prediction', 'over')
    op.drop_column('prediction', 'home_win')
    op.drop_column('prediction', 'home_goals_pmf')
    op.drop_column('prediction', 'draw')
    op.drop_column('prediction', 'away_win')
    op.drop_column('prediction', 'away_goals_pmf')
    # ### end Alembic commands ###
