"""empty message

Revision ID: e3eb8d9b0117
Revises: ed4175d4a2e9
Create Date: 2017-03-01 14:40:35.564653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3eb8d9b0117'
down_revision = 'ed4175d4a2e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('goal_difference', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('goals_against', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('goals_for', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('lost', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('played', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('points', sa.Integer(), nullable=True))
    op.add_column('teams', sa.Column('won', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'won')
    op.drop_column('teams', 'points')
    op.drop_column('teams', 'played')
    op.drop_column('teams', 'lost')
    op.drop_column('teams', 'goals_for')
    op.drop_column('teams', 'goals_against')
    op.drop_column('teams', 'goal_difference')
    # ### end Alembic commands ###
