"""empty message

Revision ID: ed4175d4a2e9
Revises: d9e67bef581b
Create Date: 2017-03-01 11:30:04.881951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed4175d4a2e9'
down_revision = 'd9e67bef581b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('teams', sa.Column('league_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'teams', 'league', ['league_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'league_id')
    op.drop_table('league')
    # ### end Alembic commands ###
