"""empty message

Revision ID: ff95ea9abd2f
Revises: 5f962fc41786
Create Date: 2017-03-07 11:05:57.633263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff95ea9abd2f'
down_revision = '5f962fc41786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fixture', sa.Column('away_goals', sa.Integer(), nullable=True))
    op.add_column('fixture', sa.Column('home_goals', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fixture', 'home_goals')
    op.drop_column('fixture', 'away_goals')
    # ### end Alembic commands ###
